services:
  - type: web
    name: irolo64-api
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 24.14.1
